---
title: "Comparison class models (RSA + BDA)"
author: "M. H. Tessler"
date: "7/21/2017"
output: github_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=6, fig.height=4, fig.crop=F, fig.pos="tb", fig.path='figs/', echo=F, warning=F, cache=F, message=F, sanitize=T)
theme_set(theme_few())
```

```{r libraries}
library(tidyverse)
library(tidyboot)
library(coda)
library(knitr)

project.path <- "~/projects/comparison-class/"
options(digits = 7)
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}
hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}
hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
```

## Behavioral data

```{r}
df.adj <- read_csv("../data/pilot-adj-endorsement-1/pilot-adj-endorsement-1-super-SG-subset.csv")
df.cc <- read_csv("../data/pilot-classElicitation-free-4/class-elicitation-free-4-cleaned-data-w-sub2.csv")

bind_rows(
  df.cc %>% 
    rename(subordinate = NP, adj_polarity = adj_positiveness, val = specific) %>%
    select(-adj, -response, -subFreq, -superFreq) %>%
    mutate(task = "comparisonClass"),
  df.adj %>%
    select(-item_cond) %>%
    rename(superordinate = super_sg, subordinate = item, adj_polarity = key) %>%
    mutate(adj_polarity = ifelse(adj_polarity == "response_pos", "positive", "negative"),
           task = "adjEndorse")
) -> df.comb
```

```{r}
df.comb %>%
  group_by(degree, superordinate, subordinate, adj_polarity, task) %>%
  tidyboot_mean(column = val) -> df.comb.bs

df.comb.wide <- left_join(
  df.comb.bs %>% ungroup() %>% filter(task == "adjEndorse") %>% 
    select(-task, -empirical_stat, -n) %>%
    rename(adj_mean = mean, adj_lower = ci_lower, adj_upper = ci_upper),
  df.comb.bs %>% ungroup() %>% filter(task == "comparisonClass") %>% 
    select(-task, -empirical_stat, -n) %>%
    rename(cc_mean = mean, cc_lower = ci_lower, cc_upper = ci_upper)
)

ggplot(df.comb.wide, aes( x = adj_mean, xmin = adj_lower, xmax = adj_upper,
                          y = cc_mean, ymin = cc_lower, ymax = cc_upper))+
  geom_point()+
  geom_errorbarh(alpha = 0.2)+
  geom_linerange(alpha = 0.2)
```

```{r}
with(df.comb.wide, cor(adj_mean, cc_mean))
```


## Model results

#### CogSci results (L1 model)

```{r load_model_results, cache = T}
m.samp <- data.frame()
for (i in 1:4){
  m.samp.i <- read_csv(
    paste("../models/sherlock/results/results-L1-S1-silenceAlt-silenceCost-corpusFreqCC-mcmc-500000_burn250000_lag50_chain", i, ".csv", 
          sep = "")
  )
  m.samp <- bind_rows(m.samp, m.samp.i %>% mutate(chain = i))
}
```

### Global parameters

```{r}
m.samp %>%
  filter(degree == "parameter") %>%
  ggplot(., aes( x = val, fill = chain) )+
  geom_histogram()+
  facet_wrap(~superordinate + subordinate, scales = 'free')
```

```{r}
m.samp.summary <- m.samp %>%
  group_by(degree, superordinate, subordinate, task, adjective) %>%
  summarize(MAP = estimate_mode(val),
            cred_upper = hdi_upper(val),
            cred_lower = hdi_lower(val))
```


### Posterior predictive

```{r}
m.samp.summary.predictive <- m.samp.summary %>%
  filter(task %in% c("adjEndorse", "subordinateCC")) %>%
  ungroup() %>%
  rename(adj_polarity = adjective)

md.summary <- left_join(
  df.comb.bs %>% mutate(task = ifelse(task == "comparisonClass", "subordinateCC", task)),
  m.samp.summary.predictive
)
```

#### Scatterplots

```{r}
ggplot(md.summary, aes( x = MAP, xmin = cred_lower, xmax = cred_upper,
                          y = mean, ymin = ci_lower, ymax = ci_upper))+
  geom_abline(intercept = 0, slope = 1, lty = 3)+
  geom_point()+
  geom_errorbarh(alpha = 0.2)+
  geom_linerange(alpha = 0.2)+
  facet_wrap(~task)+
  scale_x_continuous(limits = c(-0.01, 1.01))+
  scale_y_continuous(limits = c(-0.01, 1.01))+
  coord_fixed()
```

```{r}
with(md.summary %>% filter(task == "subordinateCC"), cor(mean, MAP))
```
#### Bar plots

```{r}
md.summary.long <- bind_rows(
  df.comb.bs %>% mutate(task = ifelse(task == "comparisonClass", "subordinateCC", task),
                        src = 'data'),
  m.samp.summary.predictive %>%
    mutate(src = 'model') %>%
    rename(mean = MAP, ci_lower = cred_lower, ci_upper = cred_upper)
)


df.adj.items <- df.adj %>%
  distinct(degree, super_sg, item, item_cond) %>%
  rename(superordinate = super_sg, subordinate = item)
  

md.summary.long %>%
  filter(task == "subordinateCC") %>%
  left_join(., df.adj.items) %>%
  ungroup() %>%
  mutate(item_cond = factor(item_cond,
                               levels = c("negative", "neutral", "positive"),
                               labels = c("low", "medium", "high")),
         subordinate = fct_reorder(subordinate, as.numeric(item_cond))) %>%
  ggplot(., 
       aes( x = subordinate, y = mean, 
            ymin = ci_lower, ymax = ci_upper, fill = adj_polarity))+  
  geom_col(position = position_dodge(0.8), width = 0.8, alpha = 0.7, color = 'black')+
  geom_linerange(position = position_dodge(0.8), color = 'black')+  
  scale_fill_brewer(palette = "Set3")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1.0, vjust = 1),
        #axis.title.x = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.line = element_line(colour = "black"))+
  facet_wrap(~degree + superordinate + src, scales = 'free', nrow = 4)+
 # theme_black()+
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1))+
  ylab("Proportion paraphrases that contain NP")+
  xlab("Subordinate Category Prior Mean")

# ggsave("../analysis/figs/bars_cc_finalExpt_pilot_byItem_wModel.png",
#        width = 17, height = 9)
```


#### Residual analysis


```{r}
md.sum.sqErr <- md.summary %>% 
  filter(task == "subordinateCC") %>%
  group_by(degree, superordinate) %>%
  summarize(model_sSqErr = sum( (mean-MAP) ^ 2))

```

Relative frequencies

```{r}
df.cc.freq.ave <- df.cc %>%
  rename(subordinate = NP, adj_polarity = adj_positiveness, val = specific) %>%
  #distinct(degree, superordinate, NP,subFreq, superFreq) %>%
  mutate(norm_freq = 0.1*log(subFreq) / (0.1*log(subFreq) + 0.1*log(superFreq)),
         exp_ratio = exp(subFreq / superFreq)) %>%
  group_by(degree, superordinate, subordinate) %>%
  summarize(mean_sub = mean(val),
            norm_freq = mean(norm_freq),
            sqErr = (mean_sub - norm_freq)^2)

df.cc.freq.ave.sum <- df.cc.freq.ave %>%
  ungroup() %>%
  group_by(degree, superordinate) %>%
  summarize(
    mean_norm_freq = mean(norm_freq),
    mean_cc_sub = mean(mean_sub),
    freq_sSqErr = sum(sqErr))

md.sum.sqErr.freq <- left_join(md.sum.sqErr, df.cc.freq.ave.sum) %>%
  mutate(err = freq_sSqErr - model_sSqErr)

ggplot(md.sum.sqErr.freq, aes( x = freq_sSqErr, y = model_sSqErr))+
  geom_point()
```

